Load Tensorflow and enable eager execution

In [4]:
import tensorflow as tf
#check tf version
tf.__version__

'2.8.0'

Load Data


In [5]:
(train_x,train_y),(_,_)=tf.keras.datasets.boston_housing.load_data(test_split=0)

65536/57026 [==================================] - 0s 0us/step


In [6]:
train_x.shape

(506, 13)

In [7]:
train_y.shape


(506,)

In [8]:
train_x.dtype

dtype('float64')

In [9]:
train_x=train_x.astype('float32')
train_y=train_y.astype('float32')

Build Model

In [20]:
#we are initializing weights and bias with zero
w=tf.zeros(shape=(13,1))
b=tf.zeros(shape=(1))

Define a function to calculate  prediction


In [21]:
def prediction(x,w,b):
  xw_matmul=tf.matmul(x,w)
  y=tf.add(xw_matmul,b)
  return y

Function to calculate loss(mean squared error)

In [22]:
def loss(y_actual,y_predicted):
  diff=y_actual-y_predicted
  sqr=tf.square(diff)
  avg=tf.reduce_mean(sqr)
  return avg

Function to train the Model
  1.Record all the mathematical steps to calculate Loss. We will record the steps using Gradient Tape
  2.Calculate Gradients of loss w.r.t weights and bias
  3.Update weights and bias based on gradients and learning rate

In [23]:
def train(x,y_actual,w,b,learning_rate=0.01):

  #record mathematical operations on 'tape' to calculate loss
  with tf.GradientTape() as t:
    t.watch([w,b])
    current_prediction=prediction(x,w,b)
    current_loss=loss(y_actual,current_prediction)
  #Calculate gradiants for loss with respect to wieghts and bias
  dw,db=t.gradient(current_loss,[w,b])

  #update weights and bias
  w=w-learning_rate*dw
  b=b-learning_rate*db
  return w,b

Start Training

In [14]:
#Train for 100 steps
for i in range(100):
  w,b=train(train_x,train_y,w,b,learning_rate=0.01)
  print("Current loss on iterations ",i," is :",loss(train_y,prediction(train_x,w,b)).numpy())
               

Current loss on iterations  0  is : 19006894000.0
Current loss on iterations  1  is : 7.446022e+17
Current loss on iterations  2  is : 2.9173267e+25
Current loss on iterations  3  is : 1.1429995e+33
Current loss on iterations  4  is : inf
Current loss on iterations  5  is : inf
Current loss on iterations  6  is : inf
Current loss on iterations  7  is : inf
Current loss on iterations  8  is : inf
Current loss on iterations  9  is : inf
Current loss on iterations  10  is : nan
Current loss on iterations  11  is : nan
Current loss on iterations  12  is : nan
Current loss on iterations  13  is : nan
Current loss on iterations  14  is : nan
Current loss on iterations  15  is : nan
Current loss on iterations  16  is : nan
Current loss on iterations  17  is : nan
Current loss on iterations  18  is : nan
Current loss on iterations  19  is : nan
Current loss on iterations  20  is : nan
Current loss on iterations  21  is : nan
Current loss on iterations  22  is : nan
Current loss on iterations  

In [15]:
#Check Weights and Bias
print('Weights:\n',w.numpy())
print('Bias: \n',b.numpy())

Weights:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
Bias: 
 [nan]


In [16]:
train_x[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ], dtype=float32)

We need to normalize data

In [17]:
from sklearn.preprocessing import Normalizer

In [18]:
transformer=Normalizer()
train_x=transformer.fit_transform(train_x)
train_x[0]


array([0.0024119 , 0.        , 0.01592969, 0.        , 0.00105285,
       0.01201967, 0.17945357, 0.00778265, 0.00782785, 0.6007879 ,
       0.04109624, 0.7767189 , 0.03663436], dtype=float32)

After normalization training model

In [25]:
#Train for 100 steps
for i in range(100):
  w,b=train(train_x,train_y,w,b,learning_rate=0.01)
  print("Current loss on iterations ",i," is :",loss(train_y,prediction(train_x,w,b)).numpy())
               

Current loss on iterations  0  is : 84.948715
Current loss on iterations  1  is : 84.93481
Current loss on iterations  2  is : 84.92191
Current loss on iterations  3  is : 84.909966
Current loss on iterations  4  is : 84.8989
Current loss on iterations  5  is : 84.88866
Current loss on iterations  6  is : 84.87916
Current loss on iterations  7  is : 84.870346
Current loss on iterations  8  is : 84.862175
Current loss on iterations  9  is : 84.85461
Current loss on iterations  10  is : 84.84757
Current loss on iterations  11  is : 84.84106
Current loss on iterations  12  is : 84.83501
Current loss on iterations  13  is : 84.829384
Current loss on iterations  14  is : 84.824165
Current loss on iterations  15  is : 84.81932
Current loss on iterations  16  is : 84.814804
Current loss on iterations  17  is : 84.81062
Current loss on iterations  18  is : 84.806725
Current loss on iterations  19  is : 84.80309
Current loss on iterations  20  is : 84.799706
Current loss on iterations  21  is :

In [26]:
#check weights and bias
print("weights :\n",w.numpy())
print('Bias :\n',b.numpy())

weights :
 [[6.9680542e-02]
 [2.6091012e-01]
 [2.2493085e-01]
 [1.4710182e-03]
 [1.1628192e-02]
 [1.3432980e-01]
 [1.4229288e+00]
 [8.3185226e-02]
 [1.8633363e-01]
 [8.2406321e+00]
 [3.9016062e-01]
 [7.4122663e+00]
 [2.6206842e-01]]
Bias :
 [11.732036]
